# highlighter: pygments
highlighter: rouge

# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://LiMingFei56.github.io/
devurl: http://localhost:4000/
name: 李鸣飞的博客
title: 李鸣飞的博客 | Dust to dust, soil to soil, ash to ash
description: "李鸣飞的博客"

my:
    displayName: 李鸣飞
    realName: MingFei Li
    realName_cn: 李鸣飞
    jobTitle: "全栈"
    contact:
        qq: 757563349@qq.com
        email: 757563349@gmail.com
        address:
            country: China
            state: Hubei
            city: Wuhan
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["C/C++", "Python", "Shell", "SQL", "JavaWeb"]
        mobile: ["Android", "iOS", "Flutter"]
        libs: ["OpenCV"]
        tools: ["NeoVim", "Git | Github", "Linux"]

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
