markdown: kramdown
permalink: /:year/:month/:day/:title/
url: https://limingfei56.github.io/
author: MingFei Li
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 15


# Gems
gems: [jekyll-paginate]
